### ISSUE TITLE
AWSDX4API - PUT & PEP

### ISSUE THREAD

**Issue by khoirunnisapk** [aws/aws-dataexchange-data-requests#11]
### Data Provider Name

PredictHQ

### Data Provider URL(s)

https://aws.amazon.com/marketplace/seller-profile?id=b82dc088-06e8-4b0c-9068-42e35f9a099b

### Cost

Free

### Delivery

API

### Company Name

-

### Description

I use this data for my project on AWS Data Exchange for APIs Challenge

**Comment by justinbchan** [comment]
Hi @khoirunnisapk -- the link you provided is for PredictHQ products already available in the AWS Data Exchange catalog. Are you looking for other data from PredictHQ?
